---
abstract: 'simple debugger that just prints out sub calls'
author:
  - 'Written by Mark Fowler <mark@twoshortplanks.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  IPC::Open3: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-SubTrace
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.6.0
resources:
  homepage: https://github.com/2shortplanks/Devel-SubTrace/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/2shortplanks/Devel-SubTrace.git
    web: https://github.com/2shortplanks/Devel-SubTrace/tree
version: 1.00
